---
  - name: Adding Base repo
    shell: curl http://192.168.43.68/repos/CentOS-Base.repo --output /etc/yum.repos.d/CentOS-Base.repo
#    get_url: 
#      url: http://192.168.43.68/repos/CentOS-Base.repo
#      dest: /etc/yum.repos.d/CentOS-Base.repo
#      mode: 0644
#   become: yes

  - name: Adding epel repo
    shell: curl http://192.168.43.68/repos/epel.repo --output /etc/yum.repos.d/epel.repo
#    get_url:
#      url: http://192.168.43.68/repos/epel.repo
#      dest:  /etc/yum.repos.d/epel.repo
#      mode: 0644
#    become: yes


  - name: Repolist
    shell: yum repolist

  
  - name: Libselinux-python dependency for lineinfile
    yum:
      name: libselinux-python
      state: latest
  
    
